name: Build and push image.

on:
  push:
    paths:
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ echo ${{ github.ref }} | cut -d/ -f3 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/synthe102/test-image:${{ env.BRANCH_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
